Restarting tasks from the task queue
oat-sa/extension-tao-task-queue pull request #125
Opened 2021-02-26 07:48 UTC by alroniks

Related task is [CGF-204](https://oat-sa.atlassian.net/browse/CGF-204)

2021-03-10 09:39 UTC, hutnikau requested changes
Updater file need to be returned back.
We will be able to get rid of them only after all Tao instances used in production will be moved to sprint >136

We still have some of them on sprint 96 (for example DEPP auth prod).

2021-03-10 09:44 UTC, alroniks commented
@hutnikau Good notice, thank you. I will return it.

2021-03-11 13:04 UTC, tikhanovichA approved these changes
It works perfectly. Could you please just revert the updater script?

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-03-11 16:44 UTC, alexeyvy approved these changes

2021-03-11 20:09 UTC, merged